In [32]:
import pandas as pd

In [33]:
spreadsheet = pd.read_csv('UNR-IDD.csv')

In [34]:
spreadsheet.columns

Index(['Switch ID', 'Port Number', 'Received Packets', 'Received Bytes',
       'Sent Bytes', 'Sent Packets', 'Port alive Duration (S)',
       'Packets Rx Dropped', 'Packets Tx Dropped', 'Packets Rx Errors',
       'Packets Tx Errors', 'Delta Received Packets', 'Delta Received Bytes',
       'Delta Sent Bytes', 'Delta Sent Packets',
       'Delta Port alive Duration (S)', 'Delta Packets Rx Dropped',
       ' Delta Packets Tx Dropped', 'Delta Packets Rx Errors',
       'Delta Packets Tx Errors', 'Connection Point', 'Total Load/Rate',
       'Total Load/Latest', 'Unknown Load/Rate', 'Unknown Load/Latest',
       'Latest bytes counter', 'is_valid', 'Table ID', 'Active Flow Entries',
       'Packets Looked Up', 'Packets Matched', 'Max Size', 'Label',
       'Binary Label'],
      dtype='object')

In [35]:
spreadsheet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37411 entries, 0 to 37410
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Switch ID                      37411 non-null  object
 1   Port Number                    37411 non-null  object
 2   Received Packets               37411 non-null  int64
 3   Received Bytes                 37411 non-null  int64
 4   Sent Bytes                     37411 non-null  int64
 5   Sent Packets                   37411 non-null  int64
 6   Port alive Duration (S)        37411 non-null  int64
 7   Packets Rx Dropped             37411 non-null  int64
 8   Packets Tx Dropped             37411 non-null  int64
 9   Packets Rx Errors              37411 non-null  int64
 10  Packets Tx Errors              37411 non-null  int64
 11  Delta Received Packets         37411 non-null  int64
 12  Delta Received Bytes           37411 non-null  int64
 13  Delta Sent Bytes               37411 non-null  int64
 14  Delta Sent Packets             37411 non-null  int64
 15  Delta Port alive Duration (S)  37411 non-null  int64
 16  Delta Packets Rx Dropped       37411 non-null  int64
 17   Delta Packets Tx Dropped      37411 non-null  int64
 18  Delta Packets Rx Errors        37411 non-null  int64
 19  Delta Packets Tx Errors        37411 non-null  int64
 20  Connection Point               37411 non-null  int64
 21  Total Load/Rate                37411 non-null  int64
 22  Total Load/Latest              37411 non-null  int64
 23  Unknown Load/Rate              37411 non-null  int64
 24  Unknown Load/Latest            37411 non-null  int64
 25  Latest bytes counter           37411 non-null  int64
 26  is_valid                       37411 non-null  bool
 27  Table ID                       37411 non-null  int64
 28  Active Flow Entries            37411 non-null  int64
 29  Packets Looked Up              37411 non-null  int64
 30  Packets Matched                37411 non-null  int64
 31  Max Size                       37411 non-null  int64
 32  Label                          37411 non-null  object
 33  Binary Label                   37411 non-null  object
dtypes: bool(1), int64(29), object(4)
memory usage: 9.5+ MB

In [36]:
import tensorflow as tf

In [37]:
import numpy as np
binlabel = spreadsheet.pop('Binary Label')
binlabel

0        Attack
1        Attack
2        Attack
3        Attack
4        Attack
          ...
37406    Attack
37407    Attack
37408    Attack
37409    Attack
37410    Attack
Name: Binary Label, Length: 37411, dtype: object

In [38]:
binlabel = [1 if x=='Attack' else 0 for x in binlabel]
binlabel = np.array(binlabel)
spreadsheet['binlabel']=binlabel

In [39]:
spreadsheet['Switch ID'] = spreadsheet['Switch ID'].replace(['of:000000000000000c', 'of:000000000000000a',
       'of:000000000000000b', 'of:0000000000000003',
       'of:0000000000000004', 'of:0000000000000001',
       'of:0000000000000002', 'of:0000000000000007',
       'of:0000000000000008', 'of:0000000000000005',
       'of:0000000000000006', 'of:0000000000000009'],[12,10,11,3,4,1,2,7,8,5,6,9])

In [40]:
spreadsheet['Port Number'] = [float(x[-1]) for x in spreadsheet['Port Number']]

In [41]:
spreadsheet['Port1']=np.zeros(len(spreadsheet))

In [42]:
spreadsheet['Port2']=np.zeros(len(spreadsheet))

In [43]:
spreadsheet['Port3']=np.zeros(len(spreadsheet))

In [44]:
spreadsheet['Port4']=np.zeros(len(spreadsheet))

In [45]:
for idx, row in spreadsheet.iterrows():
    if row['Port Number']==1.0:
        spreadsheet['Port1'].values[idx]=1
    elif row['Port Number']==2.0:
        spreadsheet['Port2'].values[idx]=1
    elif row['Port Number']==3.0:
        spreadsheet['Port3'].values[idx]=1
    elif row['Port Number']==4.0:
        spreadsheet['Port4'].values[idx]=1

In [46]:
spreadsheet.pop('Port Number')

0        1.0
1        2.0
2        3.0
3        4.0
4        1.0
        ...
37406    2.0
37407    3.0
37408    1.0
37409    2.0
37410    3.0
Name: Port Number, Length: 37411, dtype: float64

In [47]:
spreadsheet.describe()

,Switch ID,Received Packets,Received Bytes,Sent Bytes,Sent Packets,Port alive Duration (S),Packets Rx Dropped,Packets Tx Dropped,Packets Rx Errors,Packets Tx Errors,...,Table ID,Active Flow Entries,Packets Looked Up,Packets Matched,Max Size,binlabel,Port1,Port2,Port3,Port4
count,37411.000000,37411.000000,3.741100e+04,3.741100e+04,37411.000000,37411.000000,37411.0,37411.0,37411.0,37411.0,...,37411.0,37411.000000,3.741100e+04,3.741100e+04,37411.0,37411.000000,37411.000000,37411.000000,37411.000000,37411.000000
mean,6.748603,21618.897169,2.647491e+07,2.451212e+07,33626.824009,911.096415,0.0,0.0,0.0,0.0,...,0.0,88.690572,1.008636e+05,1.007444e+05,-1.0,0.899147,0.318168,0.316645,0.239528,0.125658
std,3.770270,65283.170126,3.703044e+07,3.439876e+07,88792.970378,982.113446,0.0,0.0,0.0,0.0,...,0.0,790.715343,2.350297e+05,2.350284e+05,0.0,0.301138,0.465771,0.465174,0.426801,0.331468
min,1.000000,9.000000,7.860000e+02,5.705000e+03,41.000000,26.000000,0.0,0.0,0.0,0.0,...,0.0,4.000000,8.700000e+01,3.700000e+01,-1.0,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,329.000000,9.104050e+04,5.775950e+04,347.000000,136.000000,0.0,0.0,0.0,0.0,...,0.0,5.000000,2.367000e+03,2.272000e+03,-1.0,1.000000,0.000000,0.000000,0.000000,0.000000
50%,7.000000,1170.000000,1.263052e+07,1.262658e+07,1240.000000,259.000000,0.0,0.0,0.0,0.0,...,0.0,6.000000,7.472000e+03,7.349000e+03,-1.0,1.000000,0.000000,0.000000,0.000000,0.000000
75%,10.000000,3417.000000,3.783230e+07,3.176443e+07,3968.000000,1747.000000,0.0,0.0,0.0,0.0,...,0.0,8.000000,2.343700e+04,2.322000e+04,-1.0,1.000000,1.000000,1.000000,0.000000,0.000000
max,12.000000,352772.000000,2.715925e+08,2.392430e+08,421598.000000,3317.000000,0.0,0.0,0.0,0.0,...,0.0,9987.000000,1.012574e+06,1.012439e+06,-1.0,1.000000,1.000000,1.000000,1.000000,1.000000

In [48]:
spreadsheet.head()

,Switch ID,Received Packets,Received Bytes,Sent Bytes,Sent Packets,Port alive Duration (S),Packets Rx Dropped,Packets Tx Dropped,Packets Rx Errors,Packets Tx Errors,...,Active Flow Entries,Packets Looked Up,Packets Matched,Max Size,Label,binlabel,Port1,Port2,Port3,Port4
0,12,132,9181,6311853,238,46,0,0,0,0,...,9,767,688,-1,TCP-SYN,1,1.0,0.0,0.0,0.0
1,12,187,6304498,15713,171,46,0,0,0,0,...,9,767,688,-1,TCP-SYN,1,0.0,1.0,0.0,0.0
2,12,235,6311567,8030,58,46,0,0,0,0,...,9,767,688,-1,TCP-SYN,1,0.0,0.0,1.0,0.0
3,12,59,7878,16439,182,46,0,0,0,0,...,9,767,688,-1,TCP-SYN,1,0.0,0.0,0.0,1.0
4,10,188,6304547,16497,183,46,0,0,0,0,...,7,489,403,-1,TCP-SYN,1,1.0,0.0,0.0,0.0

In [49]:
spreadsheet.pop('Max Size')
spreadsheet.pop('Table ID')
spreadsheet.pop('Delta Packets Rx Errors')
spreadsheet.pop('Delta Packets Rx Dropped')
spreadsheet.pop('Packets Tx Errors')
spreadsheet.pop('Packets Rx Errors')
spreadsheet.pop('Packets Tx Dropped')
spreadsheet.pop('Packets Rx Dropped')
spreadsheet.pop('Delta Packets Tx Errors')
spreadsheet.pop(' Delta Packets Tx Dropped')
spreadsheet.pop('is_valid')

0        True
1        True
2        True
3        True
4        True
         ...
37406    True
37407    True
37408    True
37409    True
37410    True
Name: is_valid, Length: 37411, dtype: bool

In [50]:
spreadsheet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37411 entries, 0 to 37410
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Switch ID                      37411 non-null  int64
 1   Received Packets               37411 non-null  int64
 2   Received Bytes                 37411 non-null  int64
 3   Sent Bytes                     37411 non-null  int64
 4   Sent Packets                   37411 non-null  int64
 5   Port alive Duration (S)        37411 non-null  int64
 6   Delta Received Packets         37411 non-null  int64
 7   Delta Received Bytes           37411 non-null  int64
 8   Delta Sent Bytes               37411 non-null  int64
 9   Delta Sent Packets             37411 non-null  int64
 10  Delta Port alive Duration (S)  37411 non-null  int64
 11  Connection Point               37411 non-null  int64
 12  Total Load/Rate                37411 non-null  int64
 13  Total Load/Latest              37411 non-null  int64
 14  Unknown Load/Rate              37411 non-null  int64
 15  Unknown Load/Latest            37411 non-null  int64
 16  Latest bytes counter           37411 non-null  int64
 17  Active Flow Entries            37411 non-null  int64
 18  Packets Looked Up              37411 non-null  int64
 19  Packets Matched                37411 non-null  int64
 20  Label                          37411 non-null  object
 21  binlabel                       37411 non-null  int32
 22  Port1                          37411 non-null  float64
 23  Port2                          37411 non-null  float64
 24  Port3                          37411 non-null  float64
 25  Port4                          37411 non-null  float64
dtypes: float64(4), int32(1), int64(20), object(1)
memory usage: 7.3+ MB

In [51]:
spreadsheet = spreadsheet.reindex(columns = ['Received Packets', 'Received Bytes', 'Sent Bytes',
       'Sent Packets', 'Port alive Duration (S)', 'Delta Received Packets',
       'Delta Received Bytes', 'Delta Sent Bytes', 'Delta Sent Packets',
       'Delta Port alive Duration (S)', 'Total Load/Rate',
       'Total Load/Latest', 'Unknown Load/Rate', 'Unknown Load/Latest',
       'Latest bytes counter', 'Active Flow Entries', 'Packets Looked Up',
       'Packets Matched', 'Switch ID', 'Connection Point', 'Port1', 'Port2', 'Port3', 'Port4','binlabel','Label'])

In [52]:
label = spreadsheet.pop('Label')
alias = {'TCP-SYN':1, 'PortScan':2, 'Overflow':3, 'Blackhole':4, 'Diversion':5, 'Normal':0}
newlabels = []
for x in label:
    newlabels.append(alias[x])
spreadsheet['label'] = newlabels

In [53]:
spreadsheet = spreadsheet.apply(pd.to_numeric)
spreadsheet=spreadsheet.astype(np.float32)
tf.convert_to_tensor(spreadsheet)

<tf.Tensor: shape=(37411, 26), dtype=float32, numpy=
array([[1.3200000e+02, 9.1810000e+03, 6.3118530e+06, ..., 0.0000000e+00,
        1.0000000e+00, 1.0000000e+00],
       [1.8700000e+02, 6.3044980e+06, 1.5713000e+04, ..., 0.0000000e+00,
        1.0000000e+00, 1.0000000e+00],
       [2.3500000e+02, 6.3115670e+06, 8.0300000e+03, ..., 0.0000000e+00,
        1.0000000e+00, 1.0000000e+00],
       ...,
       [1.0420000e+03, 2.5252012e+07, 7.8569760e+06, ..., 0.0000000e+00,
        1.0000000e+00, 2.0000000e+00],
       [1.4901200e+05, 1.4360115e+07, 2.9509000e+04, ..., 0.0000000e+00,
        1.0000000e+00, 2.0000000e+00],
       [2.2800000e+02, 3.0377000e+04, 2.5258600e+07, ..., 0.0000000e+00,
        1.0000000e+00, 2.0000000e+00]], dtype=float32)>

In [54]:
import sklearn.model_selection as sk
X_train, X_test = sk.train_test_split(spreadsheet, test_size=0.1)

In [55]:
X_train.drop(X_train[X_train['label']==4].index, inplace=True)

In [56]:
X_train.head()

,Received Packets,Received Bytes,Sent Bytes,Sent Packets,Port alive Duration (S),Delta Received Packets,Delta Received Bytes,Delta Sent Bytes,Delta Sent Packets,Delta Port alive Duration (S),...,Packets Looked Up,Packets Matched,Switch ID,Connection Point,Port1,Port2,Port3,Port4,binlabel,label
18303,2516.0,25428120.0,44342008.0,3092.0,2012.0,2.0,278.0,278.0,2.0,5.0,...,8147.0,7991.0,2.0,3.0,0.0,1.0,0.0,0.0,1.0,5.0
33070,513.0,6340905.0,25257660.0,1121.0,271.0,4.0,556.0,556.0,4.0,5.0,...,2957.0,2849.0,5.0,1.0,1.0,0.0,0.0,0.0,1.0,2.0
22783,2034.0,50468200.0,38013784.0,2916.0,1472.0,0.0,0.0,280.0,2.0,5.0,...,6580.0,6425.0,11.0,2.0,1.0,0.0,0.0,0.0,1.0,5.0
21835,1165.0,25244146.0,25336022.0,1850.0,992.0,0.0,0.0,280.0,2.0,5.0,...,4113.0,3991.0,11.0,2.0,1.0,0.0,0.0,0.0,1.0,5.0
34240,401.0,6319193.0,12644567.0,695.0,266.0,0.0,0.0,278.0,2.0,5.0,...,1571.0,1507.0,2.0,1.0,1.0,0.0,0.0,0.0,1.0,2.0

In [57]:
X_train.pop('label')
X_test.pop('label')

23124    3.0
8060     1.0
15175    4.0
24327    0.0
17793    5.0
        ...
8726     1.0
17001    4.0
36431    2.0
26073    0.0
9869     4.0
Name: label, Length: 3742, dtype: float32

In [58]:
Y_train = X_train.pop('binlabel')
Y_train = np.array(Y_train)

In [59]:
Y_test = X_test.pop('binlabel')
Y_test = np.array(Y_test)

In [60]:
import keras.backend as K

from tensorflow.keras.layers import Input, Normalization, Concatenate, Dense, Dropout
from tensorflow.keras.models import Model

def get_model2():
    num_features = 18  
    cat_features = 6   

    num_input = Input(shape=(num_features,), name='numerical_input')
    cat_input = Input(shape=(cat_features,), name='categorical_input')

    normalizer = Normalization()(num_input)

    combined_features = Concatenate()([normalizer, cat_input])

    hidden_layer1 = Dense(256, activation='relu')(combined_features)
    dropout1 = Dropout(0.4)(hidden_layer1)
    hidden_layer2 = Dense(128, activation='relu')(dropout1)
    dropout2 = Dropout(0.2)(hidden_layer2)
    hidden_layer3 = Dense(64, activation='relu')(dropout2)
    hidden_layer4 = Dense(6, activation='relu')(hidden_layer3)
    output_layer = Dense(1, activation='sigmoid')(hidden_layer4)

    model = Model(inputs=[num_input, cat_input], outputs=output_layer)

    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
                  loss=tf.keras.losses.BinaryCrossentropy(),
                  metrics=['accuracy'])
    
    return model

In [61]:
model2 = get_model2()
normalizer = model2.layers[1]
normalizer.adapt(X_train.iloc[:,:18])
history2 = model2.fit({'numerical_input': X_train.iloc[:,:18], 'categorical_input': X_train.iloc[:,18:]},Y_train,epochs=20,batch_size=32, validation_split=0.1, use_multiprocessing=True)

Epoch 1/20
735/735 [==============================] - 3s 2ms/step - loss: 0.1265 - accuracy: 0.9594 - val_loss: 0.0083 - val_accuracy: 0.9969
Epoch 2/20
735/735 [==============================] - 1s 2ms/step - loss: 0.0092 - accuracy: 0.9969 - val_loss: 0.0036 - val_accuracy: 0.9985
Epoch 3/20
735/735 [==============================] - 1s 2ms/step - loss: 0.0048 - accuracy: 0.9984 - val_loss: 0.0017 - val_accuracy: 0.9992
Epoch 4/20
735/735 [==============================] - 2s 2ms/step - loss: 0.0025 - accuracy: 0.9989 - val_loss: 9.1599e-04 - val_accuracy: 0.9996
Epoch 5/20
735/735 [==============================] - 1s 2ms/step - loss: 0.0017 - accuracy: 0.9994 - val_loss: 4.5740e-04 - val_accuracy: 0.9996
Epoch 6/20
735/735 [==============================] - 2s 2ms/step - loss: 0.0017 - accuracy: 0.9994 - val_loss: 2.2666e-04 - val_accuracy: 1.0000
Epoch 7/20
735/735 [==============================] - 2s 3ms/step - loss: 0.0011 - accuracy: 0.9996 - val_loss: 1.1178e-04 - val_accuracy: 1.0000
Epoch 8/20
735/735 [==============================] - 2s 3ms/step - loss: 0.0010 - accuracy: 0.9997 - val_loss: 2.1510e-04 - val_accuracy: 1.0000
Epoch 9/20
735/735 [==============================] - 2s 3ms/step - loss: 6.1529e-04 - accuracy: 0.9998 - val_loss: 4.8827e-05 - val_accuracy: 1.0000
Epoch 10/20
735/735 [==============================] - 2s 2ms/step - loss: 8.6395e-04 - accuracy: 0.9997 - val_loss: 6.4921e-05 - val_accuracy: 1.0000
Epoch 11/20
735/735 [==============================] - 2s 2ms/step - loss: 2.6370e-04 - accuracy: 1.0000 - val_loss: 1.6327e-04 - val_accuracy: 1.0000
Epoch 12/20
735/735 [==============================] - 2s 3ms/step - loss: 2.5709e-04 - accuracy: 0.9999 - val_loss: 3.8573e-05 - val_accuracy: 1.0000
Epoch 13/20
735/735 [==============================] - 2s 3ms/step - loss: 8.2495e-04 - accuracy: 0.9997 - val_loss: 7.5252e-06 - val_accuracy: 1.0000
Epoch 14/20
735/735 [==============================] - 2s 3ms/step - loss: 1.4509e-04 - accuracy: 1.0000 - val_loss: 1.3615e-04 - val_accuracy: 1.0000
Epoch 15/20
735/735 [==============================] - 2s 3ms/step - loss: 1.5365e-04 - accuracy: 1.0000 - val_loss: 2.3215e-05 - val_accuracy: 1.0000
Epoch 16/20
735/735 [==============================] - 2s 3ms/step - loss: 1.4691e-04 - accuracy: 0.9999 - val_loss: 9.2031e-05 - val_accuracy: 1.0000
Epoch 17/20
735/735 [==============================] - 2s 3ms/step - loss: 3.3926e-04 - accuracy: 0.9999 - val_loss: 3.2008e-06 - val_accuracy: 1.0000
Epoch 18/20
735/735 [==============================] - 2s 3ms/step - loss: 2.0595e-04 - accuracy: 0.9999 - val_loss: 1.6821e-06 - val_accuracy: 1.0000
Epoch 19/20
735/735 [==============================] - 2s 3ms/step - loss: 2.0075e-04 - accuracy: 1.0000 - val_loss: 2.9529e-06 - val_accuracy: 1.0000
Epoch 20/20
735/735 [==============================] - 2s 2ms/step - loss: 1.8413e-04 - accuracy: 0.9999 - val_loss: 3.0938e-06 - val_accuracy: 1.0000

In [62]:
model2.evaluate({'numerical_input': X_test.iloc[:,:18], 'categorical_input': X_test.iloc[:,18:]},Y_test)

117/117 [==============================] - 0s 1ms/step - loss: 6.9262e-07 - accuracy: 1.0000

[6.92615685693454e-07, 1.0]